Add support for using Angular pipes to transform data
l-lin/angular-datatables pull request #1494
Opened 2021-01-10 08:26 UTC by shanmukhateja

Closes #1466

2021-01-10 18:02 UTC, l-lin requested changes

2021-01-11 19:50 UTC, l-lin requested changes

2021-01-11 19:50 UTC, l-lin commented on demo/src/app/advanced/using-ng-pipe-snippet.component.ts
> +export class UsingPipeSnippetComponent implements OnInit {
__suggestion__: Do not forget to also change the class name :wink:

2021-01-12 04:07 UTC, shanmukhateja commented on demo/src/app/advanced/using-ng-pipe-snippet.component.ts
> +export class UsingPipeSnippetComponent implements OnInit {
That slipped my mind, should be fixed now @l-lin

2021-01-12 11:03 UTC, l-lin approved these changes

2021-01-12 11:03 UTC, merged