Update docs to use ngx-markdown
l-lin/angular-datatables pull request #1506
Opened 2021-01-24 13:50 UTC by shanmukhateja

2021-01-24 14:35 UTC, l-lin commented on demo/angular.json
> +              "node_modules/prism-themes/themes/prism-material-dark.css",
__suggestion__: Is PrismJS a syntax highlighting library? What's the difference with highlight.js? If it's better, we can remove the latter :)

2021-01-24 14:35 UTC, l-lin commented on demo/src/app/base-demo/base-demo.component.html
> +        <h1 class="header center-on-small-only">Zero configuration</h1>
__thoughts__: Reminder to have this removed or configurable.

2021-01-24 14:52 UTC, shanmukhateja commented on demo/angular.json
> +              "node_modules/prism-themes/themes/prism-material-dark.css",
Yes, PrismJS is a syntax highlighting library. ngx-markdown uses PrismJS for highlighting blocks of code we use. It also provides the "Copy to Clipboard" functionality when download from npm.

Yes, I do plan on removing highlight.js and its angular wrapper. I'll need to delete CJS warning suppression section in `angular.json`.

2021-01-24 14:53 UTC, shanmukhateja commented on demo/src/app/base-demo/base-demo.component.html
> +        <h1 class="header center-on-small-only">Zero configuration</h1>
Yes, this block will be configurable. I seemed to have forgotten about this.

2021-01-30 12:24 UTC, l-lin requested changes
It's way better than better! Really nice work! 

I like the home page and I noticed you updated the FAQ, nice :+1:

2021-01-30 12:24 UTC, l-lin commented on demo/src/assets/docs/basic/server-side-angular-way/source-html.md
> +```typescript
```suggestion
```html
```

2021-01-30 12:24 UTC, l-lin commented on demo/src/app/app.component.html
> +                <span class="red-text text-darken-2"> Designed and built with &lt;3 by
__question__: I'm not sure why you opt to use red here as I found having white text on blue background more readable. :confused:

2021-01-30 12:24 UTC, l-lin commented on demo/src/app/app.component.html
> +                    <iframe class="right github-stars"
__suggestion__: I think we can remove this iframe as the link to the github project is already present in the sidebar.

2021-01-31 05:10 UTC, shanmukhateja commented on demo/src/assets/docs/basic/server-side-angular-way/source-html.md
> +```typescript
Fixed.

2021-01-31 05:12 UTC, shanmukhateja commented on demo/src/app/app.component.html
> +                <span class="red-text text-darken-2"> Designed and built with &lt;3 by
The red text was a placeholder for me like a TODO. I reverted it and slightly increased font-weight to improve text visibility in larger screens.

2021-01-31 05:12 UTC, shanmukhateja commented on demo/src/app/app.component.html
> +                    <iframe class="right github-stars"
Fixed.

2021-01-31 09:52 UTC, l-lin approved these changes

2021-01-31 09:53 UTC, merged