dtInstance doesn't return Promise
l-lin/angular-datatables pull request #1548
Opened 2021-05-13 09:51 UTC by shanmukhateja

- Also updated docs and demo project

Getting this off the list before upgrade to v12

2021-05-13 12:18 UTC, l-lin reviewed
__issue__: I added the promise feature because there were cases where the dtOptions comes from the server. See https://l-lin.github.io/angular-datatables/#/advanced/load-dt-options-with-promise

2021-05-13 17:22 UTC, l-lin requested changes
__issue__: The basic example "angular-way" doesn't seem to work with this change.

__suggestion__: This is a breaking change. We should not forget to add this information when releasing the newest version. Maybe add this change only in version 12, as it's a major version?

2021-05-13 17:22 UTC, l-lin commented on src/angular-datatables.directive.ts
> +              const index = columns.findIndex(e => e.data == el.data);
__chore__: This variable `index` is shadowing the previous variable `index`. We need to rename it. Moreover, the equality must be `===` instead.

```suggestion
              const columnIndex = columns.findIndex(e => e.data === el.data);
```

2021-05-13 17:22 UTC, l-lin commented on src/angular-datatables.directive.ts
> +              const i = columns.findIndex(e => e.data == el.data);
__chore__: Same here with the equality.

```suggestion
              const i = columns.findIndex(e => e.data === el.data);
```

2021-05-14 02:41 UTC, shanmukhateja commented
@l-lin thanks for the suggested changes. I've added them as requested.

And yes. I do not plan on backporting this PR to older versions.  It will be a v12+ thing only. 

We talked about this over email a few months ago, remember? I also remember attaching a git patch as POC for this.

I'm looking into angular way bug, will update when fixed.

2021-05-14 08:41 UTC, l-lin requested changes
Sorry, my memory is quite bad.

2021-05-14 08:41 UTC, l-lin commented on src/angular-datatables.directive.ts
> +              const cellFromIndex = row.childNodes.item(index);
```suggestion
              const cellFromIndex = row.childNodes.item(columnIndex);
```

2021-05-14 17:13 UTC, shanmukhateja commented
Hey, I've realised this feature isn't going to work with how we setup datatables.net library.

I'm closing this for now with hope to revive it in the future, maybe Angular v13?

2021-05-14 17:13 UTC, closed without merging