Add unit tests to demo project
l-lin/angular-datatables pull request #1579
Opened 2021-08-01 10:10 UTC by shanmukhateja

I'm opening this PR as continuation to #1529 I couldn't re-open my previous PR so here we go again!

**Features:**

Provides unit tests for following entities:

[ x ] Basic examples
[ x ] Advanced examples<sup>1</sup>

Unit test for NgTemplateRef component isn't working due to a race condition with `dtOptions` `Input` binding on the directive and `dtTrigger` inside component's `ngAfterViewInit`.

I might cover unit tests for Extensions examples in a future PR but this takes precendence.   

Closes #1513 

<sup>1. all except "Using NgTemplateRef" component.

2021-08-01 14:43 UTC, l-lin commented
Nice! :+1: 

Some suggestion: I noticed we don't have any CI on the demo project. We should add another Github action workflow to run the tests on the demo project.

I tried to run the tests in local and I got some errors: 

```
./src/app/app.component.css - Error: Module build failed (from ./node_modules/raw-loader/dist/cjs.js):
TypeError: (0 , _schemaUtils.validate) is not a function
    at Object.rawLoader (/home/llin/perso/angular-datatables/demo/node_modules/raw-loader/dist/index.js:18:29)
```

I'm not sure what I'm missing...

2021-08-01 16:49 UTC, shanmukhateja commented
@l-lin  that's what I'm planning on doing next. I'll create the workflow after we merge this PR.

Could you try deleting `node_modules`,`package-lock.json` and run `npm install`? 

Also, in order to merge this PR, I need to create a test case for NgTemplateRef which is currently in a race condition as explained above. This involves adding support for `dtTrigger.next()` and `displayTable` to accept `dtOptions` parameter to update the internal variable inside `displayTable`. Do I need a new branch for this or should I apply it here?

2021-08-02 07:49 UTC, l-lin commented
> @l-lin that's what I'm planning on doing next. I'll create the workflow after we merge this PR.

:ok_hand: 

> Could you try deleting `node_modules`,`package-lock.json` and run `npm install`?

Indeed, the `package-lock.json` was the issue...

> Also, in order to merge this PR, I need to create a test case for NgTemplateRef which is currently in a race condition as explained above. This involves adding support for `dtTrigger.next()` and `displayTable` to accept `dtOptions` parameter to update the internal variable inside `displayTable`. Do I need a new branch for this or should I apply it here?

Since it looks like some change in the library code, it would be best to update in another PR.

2021-08-08 05:00 UTC, shanmukhateja commented
@l-lin please check if the unit tests passed and the unit test itself is suitable for the component(s).

Finally, I can see the finish line on this.

2021-08-08 09:42 UTC, l-lin commented
__issue__: Some tests are not passing:

- UsingNgTemplateRefComponent > should have title "Using Angular TemplateRef"

```
error properties: Object({ longStack: 'TypeError: Cannot read property 'aDataSort' of undefined
    at _fnSortFlatten (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:5929:1)
    at _fnSortingClasses (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:6267:1)
    at loadedInit (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1213:1)
    at HTMLTableElement.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1311:1)
    at Function.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:385:1)
    at jQuery.fn.init.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:207:1)
    at jQuery.fn.init.DataTable (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:869:1)
    at jQuery.fn.i ...
```

- UsingNgTemplateRefComponent > should create the app

```
error properties: Object({ longStack: 'TypeError: Cannot read property 'aDataSort' of undefined
    at _fnSortFlatten (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:5929:1)
    at _fnSortingClasses (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:6267:1)
    at loadedInit (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1213:1)
    at HTMLTableElement.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1311:1)
    at Function.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:385:1)
    at jQuery.fn.init.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:207:1)
    at jQuery.fn.init.DataTable (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:869:1)
    at jQuery.fn.i ...
```

- UsingNgTemplateRefComponent > should have firstName, lastName columns have text in uppercase

```
TypeError: Cannot read property 'querySelector' of null
    at http://localhost:9876/_karma_webpack_/webpack:/src/app/advanced/using-ng-template-ref.component.spec.ts:73:43
    at <Jasmine>
    at fulfilled (http://localhost:9876/_karma_webpack_/main.js:1436:58)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:126:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
    at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1276:1
    at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:406:1)
    at ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:157:1)
```

- UsingNgTemplateRefComponent

```
error properties: Object({ longStack: 'TypeError: Cannot read property 'aDataSort' of undefined
    at _fnSortFlatten (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:5929:1)
    at _fnSortingClasses (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:6267:1)
    at loadedInit (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1213:1)
    at HTMLTableElement.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1311:1)
    at Function.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:385:1)
    at jQuery.fn.init.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:207:1)
    at jQuery.fn.init.DataTable (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:869:1)
    at jQuery.fn.i ...
```

2021-08-08 15:14 UTC, l-lin requested changes

2021-08-08 15:14 UTC, l-lin commented on demo/src/app/advanced/individual-column-filtering.component.spec.ts
> +    expect(instance.rows({ page: 'current' }).count()).toBe(1);
__suggestion (non-blocking)__: We can compare the actual result with the expected filtered list from `data/data.json`. Nevertheless, the content of the example data did not change since the beginning of this project, so if it's too much hassle, we can ignore this suggestion.

2021-08-08 15:14 UTC, l-lin commented on demo/src/app/basic/with-ajax.component.spec.ts
> +        WithAjaxComponent,
__suggestion (non-blocking)__: I noticed the creation `fixture` is similar to all tests, except the declaration of the component to test. Maybe we can create a `FixtureFactory` or something alike in the test source to factorize this fixture creation.

2021-08-08 15:14 UTC, l-lin commented on demo/src/app/basic/with-ajax.component.spec.ts
> +/* tslint:disable:no-unused-variable */
__question__: Why disable this rule? Are there any unused variable?

2021-08-08 15:14 UTC, l-lin commented on demo/src/app/advanced/using-ng-template-ref.component.ts
> +      // fix: unit test fails if dtOptions isn't sent with dtTrigger
__suggestion__: Adding a comment to explain why we needed to add the `this.dtOptions` in the argument is a great idea, but I'm not sure adding the prefix `fix:` is necessarily. We can add more information in the comment on why it fails the unit tests (race condition).

2021-08-11 03:47 UTC, shanmukhateja commented on demo/src/app/advanced/individual-column-filtering.component.spec.ts
> +    expect(instance.rows({ page: 'current' }).count()).toBe(1);
Yes I thought about it and I've decided to do a "refactor tests" PR which will include this. I want to keep this PR "straight to the point".

2021-08-11 03:48 UTC, shanmukhateja commented on demo/src/app/basic/with-ajax.component.spec.ts
> +        WithAjaxComponent,
Yes as mentioned above, I've decided to do a "refactor tests" PR which will include this. I want to keep this PR "straight to the point".

2021-08-11 03:48 UTC, shanmukhateja commented on demo/src/app/basic/with-ajax.component.spec.ts
> +/* tslint:disable:no-unused-variable */
my bad. Fixed.

2021-08-11 03:48 UTC, shanmukhateja commented on demo/src/app/advanced/using-ng-template-ref.component.ts
> +      // fix: unit test fails if dtOptions isn't sent with dtTrigger
Done.

2021-08-11 03:49 UTC, shanmukhateja commented
> **issue**: Some tests are not passing:
> 
>     * UsingNgTemplateRefComponent > should have title "Using Angular TemplateRef"
> 
> 
> ```
> error properties: Object({ longStack: 'TypeError: Cannot read property 'aDataSort' of undefined
>     at _fnSortFlatten (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:5929:1)
>     at _fnSortingClasses (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:6267:1)
>     at loadedInit (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1213:1)
>     at HTMLTableElement.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1311:1)
>     at Function.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:385:1)
>     at jQuery.fn.init.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:207:1)
>     at jQuery.fn.init.DataTable (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:869:1)
>     at jQuery.fn.i ...
> ```
> 
>     * UsingNgTemplateRefComponent > should create the app
> 
> 
> ```
> error properties: Object({ longStack: 'TypeError: Cannot read property 'aDataSort' of undefined
>     at _fnSortFlatten (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:5929:1)
>     at _fnSortingClasses (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:6267:1)
>     at loadedInit (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1213:1)
>     at HTMLTableElement.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1311:1)
>     at Function.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:385:1)
>     at jQuery.fn.init.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:207:1)
>     at jQuery.fn.init.DataTable (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:869:1)
>     at jQuery.fn.i ...
> ```
> 
>     * UsingNgTemplateRefComponent > should have firstName, lastName columns have text in uppercase
> 
> 
> ```
> TypeError: Cannot read property 'querySelector' of null
>     at http://localhost:9876/_karma_webpack_/webpack:/src/app/advanced/using-ng-template-ref.component.spec.ts:73:43
>     at <Jasmine>
>     at fulfilled (http://localhost:9876/_karma_webpack_/main.js:1436:58)
>     at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
>     at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:126:1)
>     at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
>     at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)
>     at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1276:1
>     at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:406:1)
>     at ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:157:1)
> ```
> 
>     * UsingNgTemplateRefComponent
> 
> 
> ```
> error properties: Object({ longStack: 'TypeError: Cannot read property 'aDataSort' of undefined
>     at _fnSortFlatten (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:5929:1)
>     at _fnSortingClasses (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:6267:1)
>     at loadedInit (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1213:1)
>     at HTMLTableElement.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:1311:1)
>     at Function.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:385:1)
>     at jQuery.fn.init.each (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jquery/dist/jquery.js:207:1)
>     at jQuery.fn.init.DataTable (http://localhost:9876/_karma_webpack_/webpack:/node_modules/datatables.net/js/jquery.dataTables.js:869:1)
>     at jQuery.fn.i ...
> ```

@l-lin Do you know of a way to reproduce this issue so that I can investigate it?

2021-08-13 17:43 UTC, l-lin commented on demo/src/app/advanced/load-dt-options-with-promise.component.spec.ts
> +/* tslint:disable:no-unused-variable */
__chore__: Remove this rule in all test files.

2021-08-13 17:43 UTC, l-lin commented on demo/src/app/basic/with-ajax.component.spec.ts
> +/* tslint:disable:no-unused-variable */
Can you remove it on all test files please?

2021-08-13 17:50 UTC, l-lin commented
> @l-lin Do you know of a way to reproduce this issue so that I can investigate it?

This is what I did:

```bash
cd /path/to/demo
rm package-lock.json && npm i --force && CHROME_BIN=/snap/bin/chromium npm test
```

Maybe you can push your package-lock.json?

2021-08-14 15:49 UTC, shanmukhateja commented
> Maybe you can push your package-lock.json?

Here you go:

[package-lock.json.zip](https://github.com/l-lin/angular-datatables/files/6986754/package-lock.json.zip)

2021-08-14 15:49 UTC, shanmukhateja commented on demo/src/app/basic/with-ajax.component.spec.ts
> +/* tslint:disable:no-unused-variable */
Done.

2021-08-16 07:05 UTC, l-lin commented
Mmh, I still got the error, so it's not the `package-lock.json`. Maybe it's only on my computer, we'll see when we will integrate the CI.

2021-08-16 07:06 UTC, merged