Angular 13 support
l-lin/angular-datatables pull request #1617
Opened 2021-11-13 16:41 UTC by shanmukhateja

**Features:**
- Upgrades lib, demo app to v13
- Fixes unit tests not working

**Blocker:** #1612

2021-11-14 08:56 UTC, l-lin requested changes

2021-11-14 08:56 UTC, l-lin commented on demo/package-lock.json
> +      "resolved": "/tmp/node-local-install-1c6963x6rkvwka4qf/angular-datatables-12.0.1.tgz",
__issue__: Unfortunately, changing this field makes the CI build fail. Indeed, it's specific to your local installation, so the path is in the CI is not the same.

2021-11-14 12:10 UTC, shanmukhateja commented on demo/package-lock.json
> +      "resolved": "/tmp/node-local-install-1c6963x6rkvwka4qf/angular-datatables-12.0.1.tgz",
@l-lin  This has been resolved in later commit.

2021-11-15 08:27 UTC, merged

2021-11-15 08:27 UTC, l-lin commented
LGTM :+1: