Add ngPipeArgs and correct responsive installation
l-lin/angular-datatables pull request #1642
Opened 2022-02-25 14:50 UTC by adrien-syrotnik

Hi,

I added the `ngPipeArgs` option with a test in `demo/src/app/advanced/using-ng-pipe.component.spec.ts` file. I chose to take the data ID and convert it to currency because I didn't know how to import data.

I also saw that the responsive installation was wrong, I decided to fix it.

Finally, this is my first pull request, if I did something wrong, don't hesitate to tell me.

Regards,
Adrien.

2022-02-26 10:37 UTC, shanmukhateja requested changes
It's a good start for PR! Just needs a handful of changes.

2022-02-26 10:37 UTC, shanmukhateja commented on demo/src/app/advanced/using-ng-pipe.component.spec.ts
> +      let pipeInstance = app.pipeCurrencyInstance;
This can be `const` as we don't re-declare `pipeInstance`.

2022-02-26 10:37 UTC, shanmukhateja commented on demo/src/app/advanced/using-ng-pipe.component.spec.ts
> +      console.log(NumberFromData)
Forgot to remove these, I assume?

2022-02-26 10:37 UTC, shanmukhateja commented on package.json
> +  "version": "13.1.0",
Please revert this. I'll update the version at a later date.

2022-02-26 10:37 UTC, shanmukhateja commented on demo/src/assets/docs/extensions/responsive/installation.md
> -npm install datatables.net-colreorder --save
Can we move "responsive installation fix" to a different PR? We try not to mix unrelated code changes in single PR.

2022-02-27 13:04 UTC, adrien-syrotnik reviewed
Hi,
So,I changed everything you told me :
- Remove version 13.1.0
- Remove responsive installation part
- Remove console.log() (Yes it was a mistake 😅)
- Use `||` instead of `? :`
- Replace `let` by `const`

For me, I think it's all good !

Regards,
Adrien.

2022-02-28 14:49 UTC, shanmukhateja approved these changes
looks good

2022-03-01 10:23 UTC, l-lin approved these changes

2022-03-01 17:38 UTC, merged