Fixed columns extension documentation added
l-lin/angular-datatables pull request #1761
Opened 2023-12-09 21:19 UTC by bikos

2023-12-12 18:30 UTC, shanmukhateja commented
Hey, thanks for the PR.

I completely forgot about this.

2023-12-12 18:33 UTC, shanmukhateja requested changes
left feedback

2023-12-12 18:33 UTC, shanmukhateja commented on demo/angular.json
> +              "node_modules/datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.css"
Can you use dataTables CSS & JS instead of Bootstrap?

We intend to keep the styling of components to as little as possible.

2023-12-12 18:33 UTC, shanmukhateja commented on demo/package.json
> +    "datatables.net-fixedcolumns-bs4": "^4.3.0",
same as above

2023-12-13 04:08 UTC, bikos commented
Updated.

2023-12-15 14:49 UTC, l-lin approved these changes

2023-12-16 05:08 UTC, shanmukhateja requested changes
I still see bootstrap :(

2023-12-16 05:08 UTC, shanmukhateja commented on demo/src/assets/docs/extensions/fixedcolumns/installation.md
> +              "node_modules/datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.css"
I think this should be `-dataTables.css`

2023-12-17 04:51 UTC, bikos commented on demo/src/assets/docs/extensions/fixedcolumns/installation.md
> +              "node_modules/datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.css"
This is  the officially supported css for the extension, i'll update with alternative method from my earlier PR. Insert the styles for new classes added by the extension.

2023-12-17 04:58 UTC, bikos commented on demo/src/assets/docs/extensions/fixedcolumns/installation.md
> +              "node_modules/datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.css"
I've left the alternative installation guide as well if people really want.

2023-12-17 07:23 UTC, merged

2024-03-04 16:25 UTC, bikos commented
@l-lin @shanmukhateja  seems like we need to still make a release to make this available in the docs.

2024-03-05 10:22 UTC, l-lin commented
Oops, forgotten. It's deployed: https://l-lin.github.io/angular-datatables/#/extensions/fixed-columns