DT v2 + Project structure upgrades
l-lin/angular-datatables pull request #1783
Opened 2024-04-06 18:28 UTC by shanmukhateja

Closes #1777 and #1780 

Feel free to test this branch for issues. I have verified the functionality using `npm test`.

Also, I suggest cloning this branch in a separate directory due to differences in project structure and `devDependencies`.

2024-04-06 18:33 UTC, shanmukhateja commented
@l-lin I may have broken GitHub CI flow with these changes. We simply need to update `npm` commands used in the workflow file and test it back-to-back.

If you can spare some time, please look into this. It might take me a while to check this due to some personal commitments. :-^)

2024-04-09 12:18 UTC, shanmukhateja commented
I still need to update documentation pages and DEVELOPER.md

2024-04-19 18:00 UTC, l-lin requested changes
__chore__: We need another change on the documentation where we need to specify that angular-datatables will only support datatables v2 starting from version X.

2024-04-19 18:00 UTC, l-lin commented on package.json
> +  "typings": "src/index.d.ts",
__issue__: I think the folder is not correct as there's no `src` folder.

2024-04-19 18:00 UTC, l-lin commented on package.json
> +    "link:lib": "rimraf node_modules/angular-datatables && npm run build:lib && linklocal",
__chore__: Can you also update/delete the `demo/README.md` that still has reference on the `install-local` tool?

2024-04-19 18:00 UTC, l-lin commented on DEVELOPER.md
__chore__: The instructions above are obsolete and need to be updated to use the new commands.

2024-04-19 18:00 UTC, l-lin commented on demo/src/app/app.component.css
>  }
__issue__: I don't know if there's something missing, when I ran the demo with `npm start`, the search bar is not well rendered:

![image](https://github.com/l-lin/angular-datatables/assets/5452304/214097b4-71da-4702-ba03-21a024d0f294)

2024-04-19 18:09 UTC, shanmukhateja commented
Hey @l-lin 

Glad to know you're back.

I have just closed the laptop for the night so let me check and update the PR tomorrow (IST timezone).

:)

2024-04-20 03:28 UTC, shanmukhateja commented on demo/src/app/extensions/buttons-extension.component.ts
> +          exportOptions: [1, 2, 3]
In DT v2, the property name was changed.

2024-04-20 07:41 UTC, shanmukhateja commented on demo/src/app/extensions/colreorder-extension.component.ts
> -        fixedColumnsRight: 2
Fixed :)

2024-04-20 07:41 UTC, shanmukhateja commented on lib/public_api.ts
> +export * from './index';
Fixed :)

2024-04-20 07:41 UTC, shanmukhateja commented on package.json
> +  "typings": "src/index.d.ts",
Good catch! Fixed :)

2024-04-20 07:42 UTC, shanmukhateja commented on package.json
> +    "link:lib": "rimraf node_modules/angular-datatables && npm run build:lib && linklocal",
Fixed :)

2024-04-20 07:42 UTC, shanmukhateja commented on DEVELOPER.md
Fixed :)

2024-04-20 07:45 UTC, shanmukhateja commented on demo/src/app/app.component.css
>  }
This is happening due to incompatibility between materializecss and datatables.net-dt styling.

Fixed :)

2024-04-20 07:47 UTC, shanmukhateja commented
@l-lin Please don't merge the PR just yet. I need to test `ng add` with Bootstrap + DT v2.

2024-04-20 13:38 UTC, l-lin requested changes
> **chore**: We need another change on the documentation where we need to specify that angular-datatables will only support datatables v2 starting from version X.

I was only expecting a small quote on the FAQ page. What you implemented is way better :+1: 

However, I think we need to invert the sources, i.e. `md(HTML|TS)` for source on DT v2 and have a `md(HTML|TS)DTV1` for V1 instead.

Indeed, we will update and maintain the documentation for DT v2 and the ones for DT V1 will not be touched (or will be deleted in the future). In other words, we should use variable names with suffix/prefix for special cases and have the "standard" variable name for the documentation we need to keep up-to-date.

The benefit is double:

- it's implicit that "standard" variable name like "mdHTML" is the main one
- if we delete the documentation for legacy DT v1, it's easier to do it by searching the keyword "v1" (or legacy?)

What do you think?

2024-04-20 13:38 UTC, l-lin commented on demo/src/app/extensions/responsive-extension.component.html
> +<app-base-demo [pageTitle]="pageTitle" [mdIntro]="mdIntro" [mdInstall]="mdInstall" [mdHTML]="mdHTML" [mdTS]="mdTS" mdTSV2="mdTSV2" [template]="preview">
```suggestion
<app-base-demo [pageTitle]="pageTitle" [mdIntro]="mdIntro" [mdInstall]="mdInstall" [mdHTML]="mdHTML" [mdTS]="mdTS" [mdTSV2]="mdTSV2" [template]="preview">
```

__issue__: Missing brackets `[]`.

2024-04-21 06:28 UTC, shanmukhateja commented on demo/src/app/extensions/responsive-extension.component.html
> +<app-base-demo [pageTitle]="pageTitle" [mdIntro]="mdIntro" [mdInstall]="mdInstall" [mdHTML]="mdHTML" [mdTS]="mdTS" mdTSV2="mdTSV2" [template]="preview">
Fixed :)

2024-04-21 06:29 UTC, shanmukhateja commented
> > **chore**: We need another change on the documentation where we need to specify that angular-datatables will only support datatables v2 starting from version X.
> 
> I was only expecting a small quote on the FAQ page. What you implemented is way better 👍
> 
> However, I think we need to invert the sources, i.e. `md(HTML|TS)` for source on DT v2 and have a `md(HTML|TS)DTV1` for V1 instead.
> 
> Indeed, we will update and maintain the documentation for DT v2 and the ones for DT V1 will not be touched (or will be deleted in the future). In other words, we should use variable names with suffix/prefix for special cases and have the "standard" variable name for the documentation we need to keep up-to-date.
> 
> The benefit is double:
> 
>     * it's implicit that "standard" variable name like "mdHTML" is the main one
> 
>     * if we delete the documentation for legacy DT v1, it's easier to do it by searching the keyword "v1" (or legacy?)
> 
> 
> What do you think?

In hindsight, I should've done it this way.

Fixed in [`e473f9d` (#1783)](https://github.com/l-lin/angular-datatables/pull/1783/commits/e473f9d9a48d1a4740a7182b41d0485059894400)

2024-04-21 08:01 UTC, l-lin approved these changes

2024-04-21 08:03 UTC, merged